# Source: template-engine/templates/vernemq/manifests/certificate.yaml
##
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cluster-issuer-ca.vernemq.rdbox.192-168-10-155.nip.io
  namespace: vernemq
  labels:
    app.kubernetes.io/name: vernemq
    app.kubernetes.io/instance: vernemq
    app.kubernetes.io/component: dependency-injection
    app.kubernetes.io/part-of: vernemq.vernemq
    app.kubernetes.io/managed-by: rdbox
    rdbox.local/format: v1beta1
    rdbox.local/chart: 0.1.0
spec:
  isCA: true
  commonName: "vernemq.rdbox.192-168-10-155.nip.io"
  dnsNames:
    - vernemq.rdbox.192-168-10-155.nip.io
    - "*.vernemq.rdbox.192-168-10-155.nip.io"
  secretName: vernemq.rdbox.192-168-10-155.nip.io
  duration: 8760h
  privateKey:
    algorithm: RSA
    size: 4096
  issuerRef:
    name: cluster-issuer-ca.rdbox.192-168-10-155.nip.io
    kind: ClusterIssuer
    group: cert-manager.io
---
# Source: template-engine/templates/vernemq/manifests/ingress/host.yaml
##
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: vernemq.rdbox.192-168-10-155.nip.io
  namespace: vernemq
  labels:
    app.kubernetes.io/name: vernemq
    app.kubernetes.io/instance: vernemq
    app.kubernetes.io/component: dependency-injection
    app.kubernetes.io/part-of: vernemq.vernemq
    app.kubernetes.io/managed-by: rdbox
    rdbox.local/format: v1beta1
    rdbox.local/chart: 0.1.0
spec:
  hostname: vernemq.rdbox.192-168-10-155.nip.io
  requestPolicy:
    insecure:
      action: Route
---
# Source: template-engine/templates/vernemq/manifests/ingress/mapping.yaml
##
apiVersion: getambassador.io/v3alpha1
kind: TCPMapping
metadata:
  name: "vernemq"
  namespace: vernemq
  labels:
    app.kubernetes.io/name: vernemq
    app.kubernetes.io/instance: vernemq
    app.kubernetes.io/component: dependency-injection
    app.kubernetes.io/part-of: datawire.edge-stack
    app.kubernetes.io/managed-by: rdbox
    rdbox.local/format: v1beta1
    rdbox.local/chart: 0.1.0
spec:
  port: 32022
  service: vernemq.vernemq:1883
